### ISSUE TITLE
MVP3

### ISSUE THREAD

**Issue by IMdmp** [IMdmp/YoutubeCompose#43]
- [ ] [Better Search UI ](https://github.com/IMdmp/YoutubeCompose/issues/27)
- [ ] [Full Working player controls](https://github.com/IMdmp/YoutubeCompose/issues/28)
- [ ] [VideoPlayerScreen loading state](https://github.com/IMdmp/YoutubeCompose/issues/41)
